### ISSUE TITLE
Assertion with more than one valid expected hash values

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#19]
Single oh assertion can have more than one valid expected hash values.
Consider a function containing oh assertion. If this function is called several times and hash value changes in between those calls, the assertion will have different expected hashes for every call.

With current implementation each assertion has one expected value for the hash it checks. If function is called more than once, value of hash variable in the last call will be patched as an expected hash value. This means that this assertion will fail on the first call.

**Comment by mr-ma** [comment]
We need to avoid inserting assert in functions that are called from a loop, because we don't know how many times they're gonna be called. 
We also need to modify assert mechanism (and post patching) to account for multiple correct hash values as stated in the previous comment.

**Comment by mr-ma** [comment]
*Duplicate*

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Thursday Jan 04, 2018 at 10:59 GMT_

----

We need to avoid inserting assert in functions that are called from a loop, because we don't know how many times they're gonna be called. 
We also need to modify assert mechanism (and post patching) to account for multiple correct hash values as stated in the previous comment.

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Friday Jan 05, 2018 at 14:23 GMT_

----

*Duplicate*
