### ISSUE TITLE
FilterFunctionPass usage in OH

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#35]
Both SC and OH are using results of FilterFunctionPass. When running sc+oh with combination file following happens:
First runs FilterFunctionPass, as it is required from SC. It parses combination file and collects function names from it. SC uses results of FilterFunctionPass to create network of guards. SC also states that results of FilterFunctionPass are preserved, which ensures that FilterFunctionPass won't be run for OH.
In OH side all functions that are not in filter function info are skipped, which in most of the cases means skipping  all the functions (see 2048 game, snake). As a result OH does not insert any hashes and assertions.

Now, is it correct to use the same filter file for both SC and OH?
 In SC we add more input dependent functions if filter file does not have enough functions, which makes sure SC can construct the graph, however OH does not have equivalent solution in case if filter file does not have enough input independent functions.

**Comment by mr-ma** [comment]
I think this is not a problem. The filter functions should be seen as a set of sensitive functions, i.e. what we actually care about protecting. That said, OH should only engage if there exist some input independent functions which are flagged as sensitive. 
For SC we have `connectivity-level` as a security requirement, that's why we include other functions... @anahitH Is this clear now?

**Comment by anahitH** [comment]
Yes it's clear now, thanks

**Comment by mr-ma** [comment]
<a href="https://github.com/mr-ma"><img src="https://avatars1.githubusercontent.com/u/4548085?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mr-ma](https://github.com/mr-ma)**
_Monday Feb 05, 2018 at 13:49 GMT_

----

I think this is not a problem. The filter functions should be seen as a set of sensitive functions, i.e. what we actually care about protecting. That said, OH should only engage if there exist some input independent functions which are flagged as sensitive. 
For SC we have `connectivity-level` as a security requirement, that's why we include other functions... @anahitH Is this clear now?

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Monday Feb 05, 2018 at 18:19 GMT_

----

Yes it's clear now, thanks
