### ISSUE TITLE
Infinite recursive calls in path functions

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#42]
In case if a function recursively calls itself, there will be infinite recursive calls, when extracting path functions.
Original function will call extracted one, which contains recursive call, this in its turn will call original and call chain will continue.
Consider following example:

void f() {
   f_1();
   .............
   f();
}

void f_1() {
    ............
    f();
}

**Comment by anahitH** [comment]
This bug is irrelevant with the current implementation of short range hash computation.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Tuesday Apr 17, 2018 at 21:13 GMT_

----

This bug is irrelevant with the current implementation of short range hash computation.
