### ISSUE TITLE
Utilize short range hash on loop blocks - better coverage

### ISSUE THREAD

**Issue by mr-ma** [tum-i22/sip-oblivious-hashing#64]

**Comment by anahitH** [comment]
Apply short range oh to data independent loop blocks. In order to have an assertion with a single valid hash value insert assertion for loop paths to loop exit block. If a given loop is data independent it will either have deterministic number of iteration or no iteration at all. Thus hash variable at exit block should either have a default value (e.g. -1) or precomputed value.
In order to be processed by short range OH loop should not only be data independent but it also should not depend on any argument of the function.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday May 02, 2018 at 17:25 GMT_

----

Apply short range oh to data independent loop blocks. In order to have an assertion with a single valid hash value insert assertion for loop paths to loop exit block. If a given loop is data independent it will either have deterministic number of iteration or no iteration at all. Thus hash variable at exit block should either have a default value (e.g. -1) or precomputed value.
In order to be processed by short range OH loop should not only be data independent but it also should not depend on any argument of the function.
