### ISSUE TITLE
SROH should not include extracted function calls in short range functions.

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#85]
Extracted functions (functions generated by -extract-functions transformation pass) contain data dependent instructions/blocks. If a call to an extracted function is included in short range path function, this may lead to binary patching problems. 
Consider an example when an extracted function has a call to scanf function (i.e. requests for an external input). If this function is called from short range path function, the execution during the patching will hang until and input is provided.

**Comment by anahitH** [comment]
SROH should skip not only calls to extracted functions, but all calls. Otherwise precomputed values for global hashes may  differ from the values computed during the real run (run of patched binary).
This can happen when a function is called from short range path function where  a hash to global hash variable is done.

**Comment by anahitH** [comment]
SROH skips extracted function calls and calls to input independent function.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday May 30, 2018 at 10:48 GMT_

----

SROH should skip not only calls to extracted functions, but all calls. Otherwise precomputed values for global hashes may  differ from the values computed during the real run (run of patched binary).
This can happen when a function is called from short range path function where  a hash to global hash variable is done.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday May 30, 2018 at 15:12 GMT_

----

Revert the part skipping call sites other than calls to extracted functions. Issues #87 and #86 should solve the problem this change was addressing.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Sunday Jun 03, 2018 at 22:21 GMT_

----

SROH skips extracted function calls and calls to input independent function.
