### ISSUE TITLE
DG fails to identify some global reachable instructions

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#88]
Some global reachable instructions are included in short range OH, as they are not identified by dg. This leads to incorrect precomputed hash values.

Consider following example from tetris game:
	```
        int *ptr;
	ptr = board;
        for (i = B_SIZE; i; i--)
		*ptr++ = i < 25 || i % B_COLS < 2 ? 7 : 0;
```
Here board is a global variable. assigning it to ptr and any use of ptr coming after should be marked as global reachable, however dg is not reporting them as such.

**Comment by anahitH** [comment]
Fixed by adding a custom check on instruction's global reachability along with having dg based check.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Wednesday May 30, 2018 at 17:24 GMT_

----

Fixed by adding a custom check on instruction's global reachability along with having dg based check.
