### ISSUE TITLE
OH instrumented binary seg faults for stringsearch program from mibench 

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#92]

**Comment by anahitH** [comment]
The crash happens for office ispell program too

**Comment by anahitH** [comment]
OH tries to hash variable which is null. It looks roughly like this

```
int* p = ...
while (p) {
   // do smth
}
```
When pointer p is data indep OH hashes it for all it's uses in loop condition, including the one when it's null. The crash happens when hashing p when it's null.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Thursday Jun 07, 2018 at 10:08 GMT_

----

The crash happens for office ispell program too

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Thursday Jun 07, 2018 at 10:49 GMT_

----

OH tries to hash variable which is null. It looks roughly like this

```
int* p = ...
while (p) {
   // do smth
}
```
When pointer p is data indep OH hashes it for all it's uses in loop condition, including the one when it's null. The crash happens when hashing p when it's null.
