### ISSUE TITLE
OH protected binary fails with incorrect hash values for cjpeg program from mibench consumer

### ISSUE THREAD

**Issue by anahitH** [tum-i22/sip-oblivious-hashing#95]

**Comment by anahitH** [comment]
Fixed by a fix of issue [#97](https://github.com/mr-ma/input-dependency-analyzer/issues/97) in input dependency analyzer.

**Comment by mr-ma** [comment]
<a href="https://github.com/anahitH"><img src="https://avatars1.githubusercontent.com/u/23015948?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anahitH](https://github.com/anahitH)**
_Friday Jun 08, 2018 at 18:14 GMT_

----

Fixed by a fix of issue [#97](https://github.com/mr-ma/input-dependency-analyzer/issues/97) in input dependency analyzer.
